version: '3.4'
services:
  cosmos.public.dappnode.eth:
    image: 'cosmos.public.dappnode.eth:0.1.4'
    build: ./build
    volumes:
      - 'cosmos:/root/.gaiad'
    tty: true
    restart: always
    ports:
      - '26656:26656'
volumes:
  cosmos: {}
