version: '3.4'
services:
  cosmos.public.dappnode.eth:
    image: 'cosmos.public.dappnode.eth:0.0.1'
    build: ./build
    volumes:
        - 'cosmos_data:/root/.gaiad'
    tty: true
volumes:
    cosmos_data: {}
